# Generated by Django 3.2.25 on 2025-12-07 04:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_rename_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='パスワード'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='予定名')),
                ('memo', models.TextField(max_length=1000, null=True, verbose_name='メモ')),
                ('private', models.IntegerField(choices=[(0, '公開'), (1, '非公開')], verbose_name='プライバシー設定')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('day', models.IntegerField(verbose_name='日')),
                ('start_hour', models.IntegerField(verbose_name='時(開始,0~23)')),
                ('start_minute', models.IntegerField(choices=[(0, '0'), (30, '30')], verbose_name='分(開始)')),
                ('end_hour', models.IntegerField(verbose_name='時(終了,0~23)')),
                ('end_minute', models.IntegerField(choices=[(0, '0'), (30, '30')], verbose_name='分(終了)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calendar_app.userid', verbose_name='ユーザーID')),
            ],
        ),
    ]
