# Generated by Django 3.2.25 on 2025-12-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_auto_20251207_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.CharField(max_length=30, verbose_name='ユーザーID'),
        ),
    ]
