# Generated by Django 3.2.25 on 2025-12-07 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20251207_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=100, verbose_name='予定名')),
                ('day_of_week', models.IntegerField(choices=[(0, '日曜'), (1, '月曜'), (2, '火曜'), (3, '水曜'), (4, '木曜'), (5, '金曜'), (6, '土曜')], verbose_name='曜日')),
                ('private', models.IntegerField(choices=[(0, '公開'), (1, '非公開')], verbose_name='プライバシー設定')),
                ('start_hour', models.IntegerField(verbose_name='時(開始,0~23)')),
                ('start_minute', models.IntegerField(choices=[(0, '0'), (30, '30')], verbose_name='分(開始)')),
                ('end_hour', models.IntegerField(verbose_name='時(終了,0~23)')),
                ('end_minute', models.IntegerField(choices=[(0, '0'), (30, '30')], verbose_name='分(終了)')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
