# Generated by Django 5.2.4 on 2025-12-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='day',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='end_minute',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='month',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_minute',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='year',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='end_minute',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start_minute',
        ),
        migrations.AddField(
            model_name='plan',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
