# Generated by Django 5.2.4 on 2025-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_remove_plan_day_remove_plan_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
