# Generated by Django 5.2.4 on 2025-12-11 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_alter_plan_end_datetime_alter_plan_start_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=100, verbose_name='予定名')),
                ('end_datetime', models.DateTimeField()),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
