# Generated by Django 5.2.4 on 2025-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='メモ'),
        ),
    ]
