# Generated by Django 5.2.4 on 2025-12-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_alter_plan_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='introduce',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='userid',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='期間の終わり'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='期間の始まり'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(verbose_name='期間の終わり'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(verbose_name='期間の始まり'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='締め切り'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=101, verbose_name='予定名'),
        ),
    ]
