# Generated by Django 5.2.4 on 2025-12-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_userid_introduce_userid_name_alter_plan_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メールアドレス'),
        ),
    ]
