# Generated by Django 5.2.4 on 2025-12-12 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_userid_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=30, verbose_name='ユーザー1')),
                ('user2', models.CharField(max_length=30, verbose_name='ユーザー2')),
                ('accept', models.IntegerField(verbose_name='承認状態')),
            ],
        ),
    ]
