# Generated by Django 5.2.4 on 2025-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.IntegerField(default=0, verbose_name='完了'),
        ),
    ]
