# Generated by Django 5.2.4 on 2025-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='calendar_app/picture/', verbose_name='アイコン'),
        ),
    ]
