# Generated by Django 5.2.4 on 2025-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0014_userid_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('meeting', '青'), ('private', '赤'), ('personal', '緑'), ('work', 'オレンジ')], default='meeting', max_length=30, verbose_name='色設定'),
        ),
    ]
